name: Generate CV PDF

on:
  push:
    branches: [ master, main ]
    paths:
      - '_data/cv.json'
      - 'scripts/generate_cv_tex.py'
      - '.github/workflows/generate-cv.yml'
  workflow_dispatch:

permissions:
  contents: write
  actions: read

jobs:
  generate-cv:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ github.token }}
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Generate LaTeX from JSON
      run: |
        cd scripts
        python generate_cv_tex.py
    
    - name: Install LaTeX
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-latex-extra texlive-fonts-recommended texlive-latex-recommended
    
    - name: Compile LaTeX to PDF
      run: |
        cd files
        pdflatex cv.tex
        # Run twice to ensure proper formatting
        pdflatex cv.tex
    
    - name: Check if PDF was generated
      run: |
        if [ -f files/cv.pdf ]; then
          echo "PDF successfully generated"
          ls -la files/cv.pdf
        else
          echo "PDF generation failed"
          exit 1
        fi
    
    - name: Upload CV PDF as artifact
      uses: actions/upload-artifact@v4
      with:
        name: cv-pdf
        path: files/cv.pdf
        
    - name: Configure Git
      run: |
        git config --global user.name 'CV Generator Bot'
        git config --global user.email 'action@github.com'
        
    - name: Commit and push changes
      run: |
        git add files/cv.pdf files/cv.tex
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Auto-update CV PDF from JSON data [skip ci]"
          git push
        fi
